### ISSUE TITLE
ymlに書かれたクラスが存在しない場合にエラーになる

### ISSUE THREAD

**Issue by muramurasan** [muramurasan/okuribito#28]

**Comment by muramurasan** [comment]
```
/Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.5/lib/active_support/inflector/methods.rb:226:in `const_get': uninitialized constant User (NameError)
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.5/lib/active_support/inflector/methods.rb:226:in `block in constantize'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.5/lib/active_support/inflector/methods.rb:224:in `each'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.5/lib/active_support/inflector/methods.rb:224:in `inject'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.5/lib/active_support/inflector/methods.rb:224:in `constantize'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.5/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/okuribito-0.1.5/lib/okuribito.rb:49:in `patch_okuribito'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/okuribito-0.1.5/lib/okuribito.rb:42:in `block in apply'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/okuribito-0.1.5/lib/okuribito.rb:41:in `each'
        from /Users/ym/works/okuribito_recorder/vendor/bundle/ruby/2.0.0/gems/okuribito-0.1.5/lib/okuribito.rb:41:in `apply'
```

こんなの

**Comment by muramurasan** [comment]
修正済み
