### ISSUE TITLE
Okuribito does not correspond to question mark operator

### ISSUE THREAD

**Issue by muramurasan** [muramurasan/okuribito#32]
```
/Users/ym/works/okuribito/lib/okuribito.rb:28:in `instance_variable_set': `@following?_i_called' is not allowed as an instance variable name (NameError)
        from /Users/ym/works/okuribito/lib/okuribito.rb:28:in `define_patch'
        from /Users/ym/works/okuribito/lib/okuribito.rb:80:in `block (3 levels) in patch_okuribito'
        from /Users/ym/works/okuribito/lib/okuribito.rb:79:in `module_eval'
        from /Users/ym/works/okuribito/lib/okuribito.rb:79:in `block (2 levels) in patch_okuribito'
        from /Users/ym/works/okuribito/lib/okuribito.rb:71:in `each'
        from /Users/ym/works/okuribito/lib/okuribito.rb:71:in `block in patch_okuribito'
        from /Users/ym/works/okuribito/lib/okuribito.rb:70:in `class_eval'
        from /Users/ym/works/okuribito/lib/okuribito.rb:70:in `patch_okuribito'
        from /Users/ym/works/okuribito/lib/okuribito.rb:42:in `block in apply'
        from /Users/ym/works/okuribito/lib/okuribito.rb:41:in `each'
        from /Users/ym/works/okuribito/lib/okuribito.rb:41:in `apply'
```

**Comment by muramurasan** [comment]
Corresponded!
